
# Syntax highlighting
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:           /:title
relative_permalinks: true

# Setup
timezone:            America/Chicago # eg. Asia/Kathmandu
locale:              en_us
name:				 'PaleoHacks.org'
title:               'PaleoHacks.org'
tagline:             'Hacking Food for Fun & Profit'
description:         'description'
url:                 http://paleohacks.org
rss:                 rss feed url
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                /assets/img/icon.png
disqus:              paleohacksdotorg # get it on https://disqus.com/admin/

author:
  name:           	 Stephen Lange
  url:            	 http://paleohacks.org
  #facebook:          username
  twitter:           stvlange
  #google_plus:       username
  #linkedin:          username
  #dribbble:          username
  #pinterest:         username
  #kiva:              username

#fb_admins:           your facebook profile id
#fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
