markdown: redcarpet
highlighter: null
permalink: /:title

url: http://paleohacks.org
baseurl: http://paleohacks.org

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed